<?php

return [
    'roles' => ['super_admin', 'admin', 'hod', 'teacher', 'student', 'accountant'],

    'pages' => [
        ['name' => 'Admin Dashboard', 'route' => 'admin.dashboard', 'module' => null],
        ['name' => 'Users', 'route' => 'admin.users.*', 'module' => null],
        ['name' => 'Teachers', 'route' => 'admin.teachers.*', 'module' => null],
        ['name' => 'Students', 'route' => 'admin.students.*', 'module' => null],
        ['name' => 'Departments', 'route' => 'admin.departments.*', 'module' => null],
        ['name' => 'Courses', 'route' => 'admin.courses.*', 'module' => null],
        ['name' => 'Subjects', 'route' => 'admin.subjects.*', 'module' => null],
        ['name' => 'Auto Timetable', 'route' => 'admin.timetable-auto.*', 'module' => 'timetable'],
        ['name' => 'Academic Phase', 'route' => 'admin.academic-phase.index', 'module' => null],
        ['name' => 'Fees', 'route' => 'admin.fees.*', 'module' => 'fees'],
        ['name' => 'Results', 'route' => 'admin.results.index', 'module' => null],
        ['name' => 'Notices', 'route' => 'admin.notices.*', 'module' => 'notice'],
        ['name' => 'Events', 'route' => 'admin.events.*', 'module' => null],
        ['name' => 'Assignments', 'route' => 'admin.assignments.*', 'module' => null],
        ['name' => 'Leaves', 'route' => 'admin.leaves.*', 'module' => 'leave'],
        ['name' => 'Audit Logs', 'route' => 'admin.audit-logs.*', 'module' => null],
        ['name' => 'Access Settings', 'route' => 'admin.settings.*', 'module' => null],

        ['name' => 'HOD Dashboard', 'route' => 'hod.dashboard', 'module' => null],
        ['name' => 'HOD Timetable', 'route' => 'hod.timetable.*', 'module' => 'timetable'],
        ['name' => 'Teacher Assignments', 'route' => 'hod.teacher-assignments.*', 'module' => null],
        ['name' => 'HOD Leaves', 'route' => 'hod.leaves.*', 'module' => 'leave'],
        ['name' => 'HOD Internal Marks', 'route' => 'hod.internal-marks.index', 'module' => null],
        ['name' => 'HOD Notices', 'route' => 'hod.notices.*', 'module' => 'notice'],

        ['name' => 'Teacher Dashboard', 'route' => 'teacher.dashboard', 'module' => null],
        ['name' => 'Teacher Attendance', 'route' => 'teacher.attendance.*', 'module' => null],
        ['name' => 'Teacher Assignments', 'route' => 'teacher.assignments.*', 'module' => null],
        ['name' => 'Teacher Internal Marks', 'route' => 'teacher.results.*', 'module' => null],
        ['name' => 'Teacher Result Search', 'route' => 'teacher.results.search', 'module' => null],
        ['name' => 'Teacher Schedule', 'route' => 'teacher.schedule.*', 'module' => 'timetable'],
        ['name' => 'Teacher Notices', 'route' => 'teacher.notices.*', 'module' => 'notice'],
        ['name' => 'Teacher Leaves', 'route' => 'teacher.leaves.*', 'module' => 'leave'],

        ['name' => 'Student Dashboard', 'route' => 'student.dashboard', 'module' => null],
        ['name' => 'Student Timetable', 'route' => 'student.schedule.*', 'module' => 'timetable'],
        ['name' => 'Student Results', 'route' => 'student.results.*', 'module' => null],
        ['name' => 'Student Attendance', 'route' => 'student.attendance.*', 'module' => null],
        ['name' => 'Student Assignments', 'route' => 'student.assignments.*', 'module' => null],
        ['name' => 'Student Fees', 'route' => 'student.fees.*', 'module' => 'fees'],
        ['name' => 'Student Notices', 'route' => 'student.notices.*', 'module' => 'notice'],
        ['name' => 'Student Leaves', 'route' => 'student.leaves.*', 'module' => 'leave'],
        ['name' => 'Profile Settings', 'route' => 'profile.edit', 'module' => null],

        ['name' => 'Accountant Dashboard', 'route' => 'accountant.dashboard', 'module' => null],
        ['name' => 'Accountant Fees', 'route' => 'accountant.fees.*', 'module' => 'fees'],
        ['name' => 'Accountant History', 'route' => 'accountant.fees.history', 'module' => 'fees'],
    ],

    'features' => [
        'edit_button_enabled' => true,
        'delete_button_enabled' => true,
        'timetable_edit_enabled' => true,
        'approve_leave_enabled' => true,
        'maintenance_mode' => false,
        'semester_lock' => false,
        'student_profile_edit_enabled' => true,
        'leave_auto_approval_toggle' => false,
    ],

    'modules' => [
        'timetable' => true,
        'fees' => true,
        'notice' => true,
        'leave' => true,
    ],

    'settings' => [
        'teacher_max_lectures_per_day' => '6',
        // working days stored as json string, default to all configured days
        'default_working_days' => json_encode(config('timetable.days', ['monday','tuesday','wednesday','thursday','friday','saturday'])),
        // how many slots to consider per day
        'default_slots_per_day' => (string) count(config('timetable.slot_blocks', [])),
    ],

    'permissions' => [
        'users.manage',
        'students.manage',
        'teachers.manage',
        'departments.manage',
        'courses.manage',
        'subjects.manage',
        'attendance.manage',
        'exams.manage',
        'results.manage',
        'notices.manage',
        'timetable.manage',
        'fees.manage',
        'leaves.manage',
        'reports.view',
        'roles.manage',
        'settings.manage',
        'audit_logs.view',
    ],

    'role_permissions' => [
        'super_admin' => ['*'],
        'admin' => [
            'users.manage',
            'students.manage',
            'teachers.manage',
            'departments.manage',
            'courses.manage',
            'subjects.manage',
            'attendance.manage',
            'exams.manage',
            'results.manage',
            'notices.manage',
            'timetable.manage',
            'fees.manage',
            'leaves.manage',
            'reports.view',
            'settings.manage',
            'audit_logs.view',
        ],
        'hod' => [
            'students.manage',
            'teachers.manage',
            'attendance.manage',
            'results.manage',
            'notices.manage',
            'timetable.manage',
            'leaves.manage',
            'reports.view',
        ],
        'teacher' => [
            'attendance.manage',
            'results.manage',
            'notices.manage',
            'timetable.manage',
        ],
        'student' => [],
        'accountant' => [
            'fees.manage',
            'reports.view',
        ],
    ],
];
